// Stage 3 — C++ AI beacon detector (OpenCV-DNN / ONNX TinyBeaconNet) tests.
//
// Covers: model loading / failure modes, input validation, Python <-> C++
// preprocessing parity, ONNX Runtime <-> OpenCV-DNN presence/heatmap/centroid
// parity (tests/fixtures/ai_parity/, frozen from Stage 2), output robustness,
// and inference determinism.
//
// Model + fixture paths are resolved from FSOC_PROJECT_SOURCE_DIR (a compile
// definition set by CMakeLists.txt to CMAKE_SOURCE_DIR) so this test runs
// unmodified from any build directory, on any clone -- no hardcoded
// /Users/... path (Stage-3 prompt §39).
//
// Same lightweight harness as tests/step1_tests.cpp .. tests/step5_tests.cpp.

#include <cctype>
#include <cmath>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>

#include "fsoc/ai_beacon_detector.hpp"

#ifndef FSOC_PROJECT_SOURCE_DIR
#error "FSOC_PROJECT_SOURCE_DIR must be defined by CMakeLists.txt"
#endif

namespace {

using fsoc::AiBeaconDetection;
using fsoc::AiBeaconDetector;
using fsoc::AiBeaconDetectorConfig;
using fsoc::AiRawInference;

int failures = 0;

void check(const bool condition, const std::string_view expression, const int line) {
    if (!condition) {
        ++failures;
        std::cerr << "FAIL line " << line << ": " << expression << '\n';
    }
}

void check_near(
    const double actual, const double expected, const double tolerance,
    const std::string_view expression, const int line) {
    if (!(std::abs(actual - expected) <= tolerance)) {
        ++failures;
        std::cerr << "FAIL line " << line << ": " << expression << " actual=" << actual
                  << " expected=" << expected << " tol=" << tolerance << '\n';
    }
}

template <typename Fn>
void check_throws_invalid_argument(Fn&& fn, const std::string_view expression, const int line) {
    bool threw = false;
    try {
        std::forward<Fn>(fn)();
    } catch (const std::invalid_argument&) {
        threw = true;
    } catch (...) {
        // wrong exception type is still a failure
    }
    check(threw, expression, line);
}

template <typename Fn>
void check_throws_runtime_error(Fn&& fn, const std::string_view expression, const int line) {
    bool threw = false;
    try {
        std::forward<Fn>(fn)();
    } catch (const std::runtime_error&) {
        threw = true;
    } catch (...) {
    }
    check(threw, expression, line);
}

#define CHECK(expr) check((expr), #expr, __LINE__)
#define CHECK_NEAR(actual, expected, tol) \
    check_near((actual), (expected), (tol), #actual " ~= " #expected, __LINE__)
#define CHECK_THROWS_INVALID(expr) \
    check_throws_invalid_argument([&] { (void)(expr); }, #expr, __LINE__)
#define CHECK_THROWS_RUNTIME(expr) \
    check_throws_runtime_error([&] { (void)(expr); }, #expr, __LINE__)

// ---------------------------------------------------------------------------
// Minimal ad-hoc JSON scalar/array reader for the flat fixture file this test
// consumes (tests/fixtures/ai_parity/expected.json). Deliberately NOT a
// general JSON parser -- the fixture is machine-generated by json.dumps
// (tools/ai/make_parity_fixture.py) with a fixed, known, purely-numeric
// shape, so adding a full JSON dependency for it would be unjustified
// (CLAUDE.md: no unnecessary dependencies; Stage-3 prompt §40).
// ---------------------------------------------------------------------------

[[nodiscard]] std::string read_file(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in.good()) {
        throw std::runtime_error("cannot read file: " + path);
    }
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

[[nodiscard]] bool is_number_char(const char c) {
    return std::isdigit(static_cast<unsigned char>(c)) != 0 || c == '-' || c == '+' || c == '.' ||
           c == 'e' || c == 'E';
}

[[nodiscard]] double read_json_number(const std::string& text, const std::string& key) {
    const std::string needle = "\"" + key + "\":";
    const auto key_pos = text.find(needle);
    if (key_pos == std::string::npos) {
        throw std::runtime_error("JSON key not found: " + key);
    }
    std::size_t pos = key_pos + needle.size();
    while (pos < text.size() && std::isspace(static_cast<unsigned char>(text[pos]))) {
        ++pos;
    }
    std::size_t end = pos;
    while (end < text.size() && is_number_char(text[end])) {
        ++end;
    }
    return std::stod(text.substr(pos, end - pos));
}

// Returns every number found inside the (possibly nested) JSON array value of
// `key`, in textual (row-major) order.
[[nodiscard]] std::vector<double> read_json_number_array(const std::string& text, const std::string& key) {
    const std::string needle = "\"" + key + "\":";
    const auto key_pos = text.find(needle);
    if (key_pos == std::string::npos) {
        throw std::runtime_error("JSON key not found: " + key);
    }
    const auto open = text.find('[', key_pos);
    if (open == std::string::npos) {
        throw std::runtime_error("JSON array not found for key: " + key);
    }
    int depth = 0;
    std::size_t close = std::string::npos;
    for (std::size_t i = open; i < text.size(); ++i) {
        if (text[i] == '[') {
            ++depth;
        } else if (text[i] == ']') {
            --depth;
            if (depth == 0) {
                close = i;
                break;
            }
        }
    }
    if (close == std::string::npos) {
        throw std::runtime_error("unterminated JSON array for key: " + key);
    }

    std::vector<double> values;
    std::size_t i = open + 1;
    while (i < close) {
        if (is_number_char(text[i]) &&
            (std::isdigit(static_cast<unsigned char>(text[i])) != 0 || text[i] == '-')) {
            std::size_t j = i;
            while (j < close && is_number_char(text[j])) {
                ++j;
            }
            values.push_back(std::stod(text.substr(i, j - i)));
            i = j;
        } else {
            ++i;
        }
    }
    return values;
}

// ---- paths ---------------------------------------------------------------

[[nodiscard]] std::string project_root() { return FSOC_PROJECT_SOURCE_DIR; }
[[nodiscard]] std::string model_path() { return project_root() + "/models/tiny_beacon_net.onnx"; }
[[nodiscard]] std::string fixture_dir() { return project_root() + "/tests/fixtures/ai_parity/"; }

[[nodiscard]] AiBeaconDetectorConfig default_config() {
    AiBeaconDetectorConfig config{};
    config.model_path = model_path();
    config.presence_threshold = 0.95;  // models/threshold.json (frozen)
    return config;
}

// A detector with threshold 0.0 always returns a value (used for parity /
// robustness checks that need the raw decoded output regardless of presence).
[[nodiscard]] AiBeaconDetectorConfig unthresholded_config() {
    AiBeaconDetectorConfig config = default_config();
    config.presence_threshold = 0.0;
    return config;
}

// ---- 1. model loads successfully ------------------------------------

void test_model_loads_successfully() {
    bool ok = true;
    try {
        const AiBeaconDetector detector{default_config()};
        (void)detector;
    } catch (...) {
        ok = false;
    }
    CHECK(ok);
}

// ---- 2. missing model fails cleanly ----------------------------------

void test_missing_model_fails_cleanly() {
    AiBeaconDetectorConfig config = default_config();
    config.model_path = project_root() + "/models/does_not_exist.onnx";
    CHECK_THROWS_RUNTIME(AiBeaconDetector{config});
}

// ---- 3. invalid configuration rejected -------------------------------

void test_invalid_config_rejected() {
    AiBeaconDetectorConfig empty_path = default_config();
    empty_path.model_path = "";
    CHECK_THROWS_INVALID(AiBeaconDetector{empty_path});

    AiBeaconDetectorConfig bad_width = default_config();
    bad_width.input_width = 0;
    CHECK_THROWS_INVALID(AiBeaconDetector{bad_width});

    AiBeaconDetectorConfig bad_height = default_config();
    bad_height.input_height = -240;
    CHECK_THROWS_INVALID(AiBeaconDetector{bad_height});
}

// ---- 4. invalid presence threshold rejected --------------------------

void test_invalid_presence_threshold_rejected() {
    AiBeaconDetectorConfig negative = default_config();
    negative.presence_threshold = -0.1;
    CHECK_THROWS_INVALID(AiBeaconDetector{negative});

    AiBeaconDetectorConfig too_high = default_config();
    too_high.presence_threshold = 1.1;
    CHECK_THROWS_INVALID(AiBeaconDetector{too_high});

    AiBeaconDetectorConfig nan_threshold = default_config();
    nan_threshold.presence_threshold = std::nan("");
    CHECK_THROWS_INVALID(AiBeaconDetector{nan_threshold});

    // Boundary-valid thresholds must NOT throw.
    bool ok = true;
    try {
        AiBeaconDetectorConfig lo = default_config();
        lo.presence_threshold = 0.0;
        const AiBeaconDetector d_lo{lo};
        AiBeaconDetectorConfig hi = default_config();
        hi.presence_threshold = 1.0;
        const AiBeaconDetector d_hi{hi};
        (void)d_lo;
        (void)d_hi;
    } catch (...) {
        ok = false;
    }
    CHECK(ok);
}

// ---- 5. empty frame rejected ------------------------------------------

void test_empty_frame_rejected() {
    const AiBeaconDetector detector{default_config()};
    CHECK_THROWS_INVALID(detector.detect(cv::Mat{}));
}

// ---- 6. wrong frame type rejected ---------------------------------------

void test_wrong_frame_type_rejected() {
    const AiBeaconDetector detector{default_config()};
    CHECK_THROWS_INVALID(detector.detect(cv::Mat(480, 640, CV_8UC3, cv::Scalar(200, 200, 200))));
    CHECK_THROWS_INVALID(detector.detect(cv::Mat(480, 640, CV_32FC1, cv::Scalar(200.0))));
    CHECK_THROWS_INVALID(detector.detect(cv::Mat(480, 640, CV_16UC1, cv::Scalar(4000.0))));
}

// ---- 7. preprocessing parity -------------------------------------------

void test_preprocessing_parity() {
    const cv::Mat input = cv::imread(fixture_dir() + "input.png", cv::IMREAD_GRAYSCALE);
    CHECK(!input.empty());
    CHECK(input.type() == CV_8UC1);
    CHECK(input.cols == 640 && input.rows == 480);

    const cv::Mat expected_ref = cv::imread(fixture_dir() + "preprocessed_ref.png", cv::IMREAD_GRAYSCALE);
    CHECK(!expected_ref.empty());
    CHECK(expected_ref.cols == 320 && expected_ref.rows == 240);

    // Mirror AiBeaconDetector's own preprocessing path exactly.
    cv::Mat resized;
    cv::resize(input, resized, cv::Size(320, 240), 0, 0, cv::INTER_AREA);
    CHECK(resized.type() == CV_8UC1);
    CHECK(resized.cols == expected_ref.cols && resized.rows == expected_ref.rows);

    const double tolerance_counts = 1.0;  // tests/fixtures/ai_parity/expected.json tolerances.preprocess_abs_count
    double max_abs_diff = 0.0;
    for (int y = 0; y < resized.rows; ++y) {
        const auto* actual_row = resized.ptr<std::uint8_t>(y);
        const auto* expected_row = expected_ref.ptr<std::uint8_t>(y);
        for (int x = 0; x < resized.cols; ++x) {
            const double diff = std::abs(static_cast<double>(actual_row[x]) - static_cast<double>(expected_row[x]));
            max_abs_diff = std::max(max_abs_diff, diff);
        }
    }
    CHECK(max_abs_diff <= tolerance_counts);
    std::cout << "  [parity] preprocessing max_abs_diff_counts=" << max_abs_diff
              << " tolerance=" << tolerance_counts << '\n';
}

// ---- 8/9/10. presence + heatmap + centroid parity (ONNX Runtime <-> OpenCV-DNN) ---

void test_output_and_centroid_parity() {
    const std::string expected_json = read_file(fixture_dir() + "expected.json");
    const cv::Mat input = cv::imread(fixture_dir() + "input.png", cv::IMREAD_GRAYSCALE);
    CHECK(!input.empty());

    const double expected_presence_logit = read_json_number(expected_json, "presence_logit");
    const double expected_presence_prob = read_json_number(expected_json, "presence_prob");
    const double expected_hm_min = read_json_number(expected_json, "heatmap_logit_min");
    const double expected_hm_max = read_json_number(expected_json, "heatmap_logit_max");
    const double expected_hm_mean = read_json_number(expected_json, "heatmap_logit_mean");
    const std::vector<double> expected_grid_rows = read_json_number_array(expected_json, "heatmap_logit_grid_rows");
    const std::vector<double> expected_grid_cols = read_json_number_array(expected_json, "heatmap_logit_grid_cols");
    const std::vector<double> expected_grid = read_json_number_array(expected_json, "heatmap_logit_grid");
    const double expected_x = read_json_number(expected_json, "decoded_x_px");
    const double expected_y = read_json_number(expected_json, "decoded_y_px");
    const double expected_peak_conf = read_json_number(expected_json, "decoded_peak_confidence");

    const double tol_presence_logit = read_json_number(expected_json, "presence_logit_abs");
    const double tol_heatmap_logit = read_json_number(expected_json, "heatmap_logit_abs");
    const double tol_decoded_px = read_json_number(expected_json, "decoded_px_abs");

    const AiBeaconDetector detector{unthresholded_config()};
    const AiRawInference raw = detector.infer_raw(input);

    // --- presence parity ---
    CHECK_NEAR(raw.presence_logit, expected_presence_logit, tol_presence_logit);
    const double presence_prob = 1.0 / (1.0 + std::exp(-raw.presence_logit));
    CHECK_NEAR(presence_prob, expected_presence_prob, 1e-3);

    // --- heatmap summary parity ---
    CHECK(raw.heatmap_logit.rows == 60 && raw.heatmap_logit.cols == 80);
    double actual_min = 1e300;
    double actual_max = -1e300;
    double actual_sum = 0.0;
    for (int y = 0; y < raw.heatmap_logit.rows; ++y) {
        const auto* row = raw.heatmap_logit.ptr<float>(y);
        for (int x = 0; x < raw.heatmap_logit.cols; ++x) {
            const double v = static_cast<double>(row[x]);
            actual_min = std::min(actual_min, v);
            actual_max = std::max(actual_max, v);
            actual_sum += v;
        }
    }
    const double actual_mean = actual_sum / (raw.heatmap_logit.rows * raw.heatmap_logit.cols);
    CHECK_NEAR(actual_min, expected_hm_min, tol_heatmap_logit * 10);  // extrema are more backend-sensitive
    CHECK_NEAR(actual_max, expected_hm_max, tol_heatmap_logit * 10);
    CHECK_NEAR(actual_mean, expected_hm_mean, tol_heatmap_logit);
    std::cout << "  [parity] presence_logit expected=" << expected_presence_logit
              << " cpp=" << raw.presence_logit
              << " abs_diff=" << std::abs(raw.presence_logit - expected_presence_logit) << '\n'
              << "  [parity] heatmap_logit min/max/mean expected=(" << expected_hm_min << ","
              << expected_hm_max << "," << expected_hm_mean << ") cpp=(" << actual_min << ","
              << actual_max << "," << actual_mean << ") mean_abs_diff="
              << std::abs(actual_mean - expected_hm_mean) << '\n';

    // --- heatmap 5x5 grid-sample parity ---
    CHECK(expected_grid_rows.size() == 5 && expected_grid_cols.size() == 5);
    CHECK(expected_grid.size() == 25);
    double grid_max_abs_diff = 0.0;
    std::size_t k = 0;
    for (const double row_d : expected_grid_rows) {
        for (const double col_d : expected_grid_cols) {
            const int iy = static_cast<int>(row_d);
            const int ix = static_cast<int>(col_d);
            const double actual_v = static_cast<double>(raw.heatmap_logit.at<float>(iy, ix));
            grid_max_abs_diff = std::max(grid_max_abs_diff, std::abs(actual_v - expected_grid[k]));
            CHECK_NEAR(actual_v, expected_grid[k], tol_heatmap_logit);
            ++k;
        }
    }
    std::cout << "  [parity] heatmap 5x5 grid max_abs_diff=" << grid_max_abs_diff
              << " tolerance=" << tol_heatmap_logit << '\n';

    // --- centroid + peak-confidence parity ---
    const auto detection = detector.detect(input);
    CHECK(detection.has_value());
    if (detection.has_value()) {
        const double dx = detection->detection.centroid_px.x_px - expected_x;
        const double dy = detection->detection.centroid_px.y_px - expected_y;
        const double euclid = std::hypot(dx, dy);
        CHECK(euclid <= tol_decoded_px);
        CHECK_NEAR(detection->detection.centroid_px.x_px, expected_x, tol_decoded_px);
        CHECK_NEAR(detection->detection.centroid_px.y_px, expected_y, tol_decoded_px);
        CHECK_NEAR(detection->peak_confidence, expected_peak_conf, 1e-3);
        std::cout << "  [parity] expected=(" << expected_x << "," << expected_y
                  << ") cpp=(" << detection->detection.centroid_px.x_px << ","
                  << detection->detection.centroid_px.y_px << ") euclidean_diff_px=" << euclid << '\n';
    }
}

// ---- 11/12. confidence finite and in [0,1] -----------------------------

void test_confidence_finite_and_bounded() {
    const AiBeaconDetector detector{unthresholded_config()};
    const cv::Mat input = cv::imread(fixture_dir() + "input.png", cv::IMREAD_GRAYSCALE);
    const auto detection = detector.detect(input);
    CHECK(detection.has_value());
    if (detection.has_value()) {
        CHECK(std::isfinite(detection->confidence));
        CHECK(detection->confidence >= 0.0 && detection->confidence <= 1.0);
        CHECK(std::isfinite(detection->peak_confidence));
        CHECK(detection->peak_confidence >= 0.0 && detection->peak_confidence <= 1.0);
        CHECK(std::isfinite(detection->inference_ms) && detection->inference_ms >= 0.0);
    }
}

// ---- 13. heatmap finite -------------------------------------------------

void test_heatmap_finite() {
    const AiBeaconDetector detector{unthresholded_config()};
    const cv::Mat input = cv::imread(fixture_dir() + "input.png", cv::IMREAD_GRAYSCALE);
    const AiRawInference raw = detector.infer_raw(input);
    bool all_finite = true;
    for (int y = 0; y < raw.heatmap_logit.rows && all_finite; ++y) {
        const auto* row = raw.heatmap_logit.ptr<float>(y);
        for (int x = 0; x < raw.heatmap_logit.cols; ++x) {
            if (!std::isfinite(static_cast<double>(row[x]))) {
                all_finite = false;
                break;
            }
        }
    }
    CHECK(all_finite);
    CHECK(std::isfinite(raw.presence_logit));
}

// ---- 14. repeated inference is deterministic ----------------------------

void test_repeated_inference_is_deterministic() {
    const AiBeaconDetector detector{unthresholded_config()};
    const cv::Mat input = cv::imread(fixture_dir() + "input.png", cv::IMREAD_GRAYSCALE);

    const AiRawInference a = detector.infer_raw(input);
    const AiRawInference b = detector.infer_raw(input);
    const AiRawInference c = detector.infer_raw(input);

    CHECK(a.presence_logit == b.presence_logit);
    CHECK(b.presence_logit == c.presence_logit);

    bool heatmaps_equal_ab = true;
    bool heatmaps_equal_bc = true;
    for (int y = 0; y < a.heatmap_logit.rows; ++y) {
        const auto* ra = a.heatmap_logit.ptr<float>(y);
        const auto* rb = b.heatmap_logit.ptr<float>(y);
        const auto* rc = c.heatmap_logit.ptr<float>(y);
        for (int x = 0; x < a.heatmap_logit.cols; ++x) {
            if (ra[x] != rb[x]) heatmaps_equal_ab = false;
            if (rb[x] != rc[x]) heatmaps_equal_bc = false;
        }
    }
    CHECK(heatmaps_equal_ab);
    CHECK(heatmaps_equal_bc);

    const auto d1 = detector.detect(input);
    const auto d2 = detector.detect(input);
    CHECK(d1.has_value() && d2.has_value());
    if (d1.has_value() && d2.has_value()) {
        CHECK(d1->detection.centroid_px.x_px == d2->detection.centroid_px.x_px);
        CHECK(d1->detection.centroid_px.y_px == d2->detection.centroid_px.y_px);
        CHECK(d1->confidence == d2->confidence);
        CHECK(d1->peak_confidence == d2->peak_confidence);
    }
}

}  // namespace

int main() {
    test_model_loads_successfully();
    test_missing_model_fails_cleanly();
    test_invalid_config_rejected();
    test_invalid_presence_threshold_rejected();
    test_empty_frame_rejected();
    test_wrong_frame_type_rejected();
    test_preprocessing_parity();
    test_output_and_centroid_parity();
    test_confidence_finite_and_bounded();
    test_heatmap_finite();
    test_repeated_inference_is_deterministic();

    if (failures == 0) {
        std::cout << "PASS: Stage-3 AI beacon detector checks passed.\n";
        return 0;
    }
    std::cerr << "FAILED: " << failures << " check(s).\n";
    return 1;
}
